### ISSUE TITLE
Don't know where to start

### ISSUE THREAD

**Issue by vtelensky** [citiususc/hipster#173]
Hello, I would like to start contribute on this nice project but I am a little bit confused where to start. Which algorithm choose to implement and so on. Could you please give me some tips what would be the best to start or on what shall I aim?

Thank you :).

**Comment by pablormier** [comment]
Hi D3ryk,

Thanks for your interest! Some time ago I've started a simple implementation of the bi-directional search https://en.wikipedia.org/wiki/Bidirectional_search algorithm to compare the performance of hipster4j vs default algos implemented in OrientDB, but I didn't finished it yet due to lack of time. Let me know if you are interested. Check also the current issues of the project to see if there is something interesting for you.

Cheers

**Comment by vtelensky** [comment]
Ok, seems like interesting algo. I am interested in that. Can you provide me some hints what have you done so far? I will start with studying algo itself.

**Comment by pablormier** [comment]
Check this implementation https://github.com/citiususc/hipster/commit/e2577974d508a5776db27d4daab554cb14d28334

I didn't tested it, I think it's a good start to play around with some graphs to see how the algorithm works :)

**Comment by vtelensky** [comment]
Thanks, I will look into that.

**Comment by vtelensky** [comment]
Hi I have tried to play around with created BSStar algorithm. I have ran into some issues which I have described here https://github.com/D3ryk/hipster/pull/1. I have created pull request in my forked version of hipster4j. Can you review it and tell me if my taughts are good or bad. In advance thanks for all your advices which you could give me.
