### ISSUE TITLE
Confuse on how to use this one for an Android app

### ISSUE THREAD

**Issue by iad24** [citiususc/hipster#174]
Im using Android Studio and Gradle.
How to I add this as dependency via Gradle?
I cant see any jar/file to download too.

Pls Help =/

**Comment by gonzalezsieira** [comment]
Hi @iad24:

You can generate a jarfile compiling the source code using Maven. On a terminal, type `mvn install`; artifacts will be placed in a directory called `target`.

With gradle you can specify the following dependency: 
`compile 'es.usc.citius.hipster:hipster-all:1.0.1'`

Note that if you only want to use the library itself (neither the extensions, nor the tests, nor the examples) you might import `hipster-core` instead of `hipster-all`, which will save you some MB in additional dependencies.

Regards,

**Comment by pablormier** [comment]
You can find the jars here: https://dl.bintray.com/hipster4j/maven/es/usc/citius/hipster/hipster-all/1.0.1/
